import path from "node:path"

import type { LeashProfile, PackageManager, ProjectFacts } from "./types.js"
import { pathExists } from "./util.js"

export interface GeneratedFile {
  path: string
  contents: string
  /** Present on disk already — apply will skip or ask before overwriting. */
  exists: boolean
  /** Hooks need the executable bit. */
  executable?: boolean
  label: string
}

export interface PlanOptions {
  adapters: string[]
  gates: boolean
  state: boolean
}

export function runPrefix(pm: PackageManager): string {
  switch (pm) {
    case "pnpm":
      return "pnpm"
    case "yarn":
      return "yarn"
    case "bun":
      return "bun run"
    case "npm":
    case "unknown":
    default:
      // npm is the safe universal fallback when no lockfile pins the manager.
      return "npm run"
  }
}

function doneDefinition(facts: ProjectFacts): string[] {
  const run = runPrefix(facts.packageManager)
  const parts: string[] = []
  const c = facts.commands
  if (c.formatCheck ?? c.format) parts.push(`\`${run} ${c.formatCheck ?? c.format}\``)
  if (c.typecheck) parts.push(`\`${run} ${c.typecheck}\``)
  if (c.lint) parts.push(`\`${run} ${c.lint}\``)
  if (c.test) parts.push(`\`${run} ${c.test}\``)
  return parts
}

export function generateAgentsMd(facts: ProjectFacts, leash: LeashProfile): string {
  const run = runPrefix(facts.packageManager)
  const done = doneDefinition(facts)
  const frameworks = facts.frameworks.length ? facts.frameworks.join(", ") : "see package.json"
  const workspace =
    facts.workspace.kind === "none" ? "single package" : `${facts.workspace.kind} workspace`
  const topDirs = facts.tree.dirs.slice(0, 14)

  const leashLines: string[] = []
  if (!leash.autonomy.commitUnasked)
    leashLines.push("- **Never commit or push unasked.** The developer drives version control.")
  if (!leash.autonomy.pushUnasked && leash.autonomy.commitUnasked)
    leashLines.push("- **Never push unasked.**")
  if (leash.scope.minimalDiffs)
    leashLines.push("- **Minimal diffs.** Never touch files outside the task's scope.")
  if (leash.vcs.ticketLinked) leashLines.push("- **Every change belongs to a ticket.**")
  if (leash.vcs.commitConvention)
    leashLines.push(`- **Commit convention:** \`${leash.vcs.commitConvention}\`.`)
  if (!leash.tooling.ghCli)
    leashLines.push(
      "- **The `gh` CLI is not available** — deliver PR/issue work as paste-ready drafts.",
    )
  if (!leash.tooling.mcpServers)
    leashLines.push("- **Third-party MCP servers are off** unless explicitly enabled.")
  if (!leash.autonomy.network) leashLines.push("- **No unprompted network access.**")
  for (const note of leash.notes) leashLines.push(`- ${note}`)

  return `# AGENTS.md

Operating contract for any AI agent working in **${facts.name}** (Claude Code, Cursor, Copilot,
and others). This is the single source of truth; per-agent files point here. Generated by
[clothaid](https://www.npmjs.com/package/clothaid) — edit this file, not the pointers.

## What this project is

<!-- One paragraph: what this app does and who it is for. Run \`clothaid brief\` to draft this
from the reckoning, then refine by hand. -->

## Stack

- **Shape:** ${workspace}${facts.packages.length ? ` (${facts.packages.length} packages)` : ""}, package manager **${facts.packageManager}**${facts.node ? `, Node ${facts.node}` : ""}.
- **Frameworks:** ${frameworks}.
- **CI:** ${facts.ci.system === "none" ? "none detected" : facts.ci.system}.

## Working rules (the leash)

${leashLines.join("\n") || "- Match local style; keep changes small and reviewable."}

## Navigate narrow

Read this contract → the repo map below → open only the files the task needs. Prefer targeted
reads over repo-wide scans; a search that misses is indistinguishable from a thing that does not
exist, so confirm against the map before concluding something is absent.

## Repo map

${topDirs.length ? topDirs.map((d) => `- \`${d.name}/\` — ${d.files} files`).join("\n") : "- (single package; list the key files here)"}

<!-- Keep this map current. As it grows, extract it into an on-demand skill so it stops loading
every session — run \`clothaid context\` to see when that pays off. -->

## Done =

${done.length ? `A change is done when these are green:\n\n${done.map((d) => `- ${d}`).join("\n")}` : `Define the check commands that gate a change (test / lint / typecheck / format).`}

## Commands

\`\`\`bash
${
  [
    facts.commands.dev && `${run} ${facts.commands.dev}`,
    facts.commands.build && `${run} ${facts.commands.build}`,
    facts.commands.test && `${run} ${facts.commands.test}`,
    facts.commands.lint && `${run} ${facts.commands.lint}`,
    facts.commands.typecheck && `${run} ${facts.commands.typecheck}`,
  ]
    .filter(Boolean)
    .join("\n") || "# add the project's key commands"
}
\`\`\`

## Session protocol

1. Read \`PROJECT_CONTEXT.md\` (current state) before starting.
2. Work in small vertical slices; keep the repo map and state doc current in the same change.
3. At session end, record what changed, what's next, and any new decisions.
`
}

export function generateClaudePointer(): string {
  return `# CLAUDE.md

Single source of truth for agent instructions lives in \`AGENTS.md\`. This pointer keeps Claude
Code aligned with every other agent — edit \`AGENTS.md\`, not this file.

@AGENTS.md
`
}

export function generateCopilotInstructions(): string {
  return `<!-- Single source of truth: ../AGENTS.md. Edit that file, not this one. -->

# Copilot instructions

Read and follow [\`AGENTS.md\`](../AGENTS.md) at the repository root — it is the operating
contract for all AI agents in this project, Copilot included.
`
}

export function generateCursorRule(): string {
  return `---
description: Project operating contract
alwaysApply: true
---

Follow the repository-root \`AGENTS.md\` as the single source of truth for how to work in this
project. It defines the stack, the leash, the repo map, and the definition of done.
`
}

export function generateProjectContext(facts: ProjectFacts): string {
  return `# PROJECT_CONTEXT.md

Ground-truth state — read this first every session. Trust it over any other doc where they differ.

_Last updated: ${new Date().toISOString().slice(0, 10)} (seeded by clothaid)._

## Stack & architecture (stable)

${facts.name} — ${facts.workspace.kind === "none" ? "single package" : `${facts.workspace.kind} workspace`}, ${facts.packageManager}. Full stack + conventions live in \`AGENTS.md\`.

## Active decisions log

_One line each (date — decision — why). Start recording here._

## Current state

### Where we are

- (describe what is built)

### Next

- (the immediate next task)

## Open questions

- (unresolved tensions)
`
}

export function generatePreCommitHook(): string {
  return `#!/usr/bin/env sh
# clothaid: process gate. Cheap, locally-knowable checks belong here (fast, blocks the commit).
# Add archive/heading/comment-style checks as your workflow grows.
exit 0
`
}

export function generatePrePushHook(facts: ProjectFacts): string {
  const run = runPrefix(facts.packageManager)
  const steps = [
    facts.commands.formatCheck ?? facts.commands.format,
    facts.commands.typecheck,
    facts.commands.lint,
  ]
    .filter((s): s is string => Boolean(s))
    .map((s) => `${run} ${s}`)
  const body = steps.length
    ? steps.map((s) => `echo "› ${s}"\n${s} || exit 1`).join("\n")
    : 'echo "clothaid: no correctness commands detected — add format:check / typecheck / lint"'
  return `#!/usr/bin/env sh
# clothaid: correctness gate. Mirrors CI cheapest-first; blocks the push on any failure.
${body}
`
}

/** Build the full set of files a setup would write, flagging which already exist. */
export async function planWorkflow(
  root: string,
  facts: ProjectFacts,
  leash: LeashProfile,
  opts: PlanOptions,
): Promise<GeneratedFile[]> {
  const out: GeneratedFile[] = []
  const add = async (rel: string, contents: string, label: string, executable = false) => {
    out.push({
      path: rel,
      contents,
      exists: await pathExists(path.join(root, rel)),
      executable,
      label,
    })
  }

  await add("AGENTS.md", generateAgentsMd(facts, leash), "Operating contract (source of truth)")
  if (opts.state)
    await add("PROJECT_CONTEXT.md", generateProjectContext(facts), "Ground-truth state")

  if (opts.adapters.includes("claude"))
    await add("CLAUDE.md", generateClaudePointer(), "Claude Code pointer")
  if (opts.adapters.includes("copilot"))
    await add(
      ".github/copilot-instructions.md",
      generateCopilotInstructions(),
      "Copilot instructions",
    )
  if (opts.adapters.includes("cursor"))
    await add(".cursor/rules/agents.mdc", generateCursorRule(), "Cursor rule")

  if (opts.gates) {
    await add(".githooks/pre-commit", generatePreCommitHook(), "Process gate (pre-commit)", true)
    await add(".githooks/pre-push", generatePrePushHook(facts), "Correctness gate (pre-push)", true)
  }

  return out
}
